name: otus-warehouse-management
on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: install poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.3
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: install dependencies
        run: poetry install
      - name: run linter
        run: poetry run ruff check
      - name: run formatter
        run: poetry run black .
      - name: check import sorting
        run: poetry run isort .
      - name: run domain tests
        run: poetry run python -m unittest ./tests/test_domain/test_services.py
      - name: run infrastructure tests
        run: poetry run python -m unittest ./tests/test_infrastructure/test_orm.py
